from _typeshed import Incomplete
from ansible.module_utils.six import PY3 as PY3, binary_type as binary_type, iteritems as iteritems, text_type as text_type
from ansible.module_utils.six.moves.collections_abc import Set as Set

__metaclass__ = type
HAS_SURROGATEESCAPE: bool

def to_bytes(obj, encoding: str = 'utf-8', errors: Incomplete | None = None, nonstring: str = 'simplerepr'): ...
def to_text(obj, encoding: str = 'utf-8', errors: Incomplete | None = None, nonstring: str = 'simplerepr'): ...
to_native = to_text

def jsonify(data, **kwargs): ...
def container_to_bytes(d, encoding: str = 'utf-8', errors: str = 'surrogate_or_strict'): ...
def container_to_text(d, encoding: str = 'utf-8', errors: str = 'surrogate_or_strict'): ...
