__all__ = ['YAML_SYNTAX_ERROR', 'YAML_POSITION_DETAILS', 'YAML_COMMON_DICT_ERROR', 'YAML_COMMON_UNQUOTED_VARIABLE_ERROR', 'YAML_COMMON_UNQUOTED_COLON_ERROR', 'YAML_COMMON_PARTIALLY_QUOTED_LINE_ERROR', 'YAML_COMMON_UNBALANCED_QUOTES_ERROR']


YAML_SYNTAX_ERROR: str
YAML_POSITION_DETAILS: str
YAML_COMMON_DICT_ERROR: str
YAML_COMMON_UNQUOTED_VARIABLE_ERROR: str
YAML_COMMON_UNQUOTED_COLON_ERROR: str
YAML_COMMON_PARTIALLY_QUOTED_LINE_ERROR: str
YAML_COMMON_UNBALANCED_QUOTES_ERROR: str
YAML_AND_SHORTHAND_ERROR: str
YAML_COMMON_LEADING_TAB_ERROR: str
